function [fitresult, gof] = createFit1(Wavelength, alphadBr)
%CREATEFIT1(WAVELENGTH,ALPHADBR)
%  Create a fit.
%
%  Data for 'Attenuation in dB' fit:
%      X Input : Wavelength
%      Y Output: alphadBr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Aug-2020 21:14:59


%% Fit: 'Attenuation in dB'.
[xData, yData] = prepareCurveData( Wavelength, alphadBr );

% Set up fittype and options.
ft = fittype( 'poly7' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Attenuation in dB' );
h = plot( fitresult, xData, yData );
legend( h, 'alphadBr vs. Wavelength', 'Attenuation in dB', 'Location', 'NorthEast' );
% Label axes
xlabel Wavelength
ylabel alphadBr
grid on


