function [fitresult, gof] = createFit1(Wavelength, Dispersion)
%CREATEFIT1(WAVELENGTH,DISPERSION)
%  Create a fit.
%
%  Data for 'Dispersion' fit:
%      X Input : Wavelength
%      Y Output: Dispersion
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Aug-2020 21:08:43


%% Fit: 'Dispersion'.
[xData, yData] = prepareCurveData( Wavelength, Dispersion );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Dispersion' );
h = plot( fitresult, xData, yData );
legend( h, 'Dispersion vs. Wavelength', 'Dispersion', 'Location', 'NorthEast' );
% Label axes
xlabel Wavelength
ylabel Dispersion
grid on


